### PR TITLE
fix(abg): allow anchors and aliases in typings

### LINKED ISSUE #1625: [Bug] No anchor support in typing
https://github.com/typesafegithub/github-actions-typing explicitly specifies that anchors are supported, but the abg says "com.charleskorn.kaml.ForbiddenAnchorOrAliasException: Parsing anchors and aliases is disabled."

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #1625

### CODE REVIEW

**Comment by Vampire** [comment]
* **#1628** <a href="https://app.graphite.dev/github/pr/typesafegithub/github-workflows-kt/1628?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/utils/YamlParsingConfig.kt [hunk 1]
```diff
@@ -9,3 +9,12 @@ internal val myYaml =
                 strictMode = false,
             ),
     )
+
+internal val myTypingsYaml =
```
Comment (krzema12) [inline action-binding-generator/src/main/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/utils/YamlParsingConfig.kt:13]: I actually thought about ditching this file, and moving the respective `Yaml` configs to `MetadataReading.kt` and `TypesProviding.kt` as private fields.

File: action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt [hunk 2]
```diff
@@ -32,20 +32,26 @@ class TypesProvidingTest :
                     separator: ','
                     list-item:
                       type: string
-                  granted-scopes:
+                  granted-scopes: &scopes-list
```
Comment (krzema12) [inline action-binding-generator/src/test/kotlin/io/github/typesafegithub/workflows/actionbindinggenerator/typing/TypesProvidingTest.kt:35]: Could we have a separate minimal unit test for the anchors & aliases, instead of piggy-backing on this one?

**Review by krzema12 — CHANGES_REQUESTED** [review]
